export const PRESETS = [
  { name: "Grand Tote",            bgImage: '/images/products/l_tote/l_navy.jpg',                                      bgColor: '#F0EBE0', widthRatio: 0.80, heightRatio: 0.33, offsetX: -0.02, offsetY:  0.09, physicalWidthInches: 25,   maxTextWidthInches: 6.75, motifSizeInches: 1.50 },
  { name: "Signature Tote",        bgImage: '/images/products/m_tote/m_navy.jpg',                                      bgColor: '#F0EBE0', widthRatio: 0.71, heightRatio: 0.34, offsetX: -0.01, offsetY:  0.12, physicalWidthInches: 18,   maxTextWidthInches: 5,    motifSizeInches: 1.25 },
  { name: "Petite Tote",           bgImage: '/images/products/s_tote/s_navy.png',                                      bgColor: '#F0EBE0', widthRatio: 0.62, heightRatio: 0.37, offsetX: -0.01, offsetY:  0.10, physicalWidthInches: 13.5, maxTextWidthInches: 4,    motifSizeInches: 1.00 },
  { name: "Petite Crossbody",      bgImage: '/images/products/s_crossbody/Screen Shot 2026-04-18 at 1.00.08 AM.png',   bgColor: '#EDE9E3', widthRatio: 0.73, heightRatio: 0.33, offsetX:  0.00, offsetY:  0.10, physicalWidthInches: 13,   maxTextWidthInches: 5,    motifSizeInches: 1.00 },
  { name: "Waffle Pouch",          bgImage: '/images/products/pouch/small_waffle_pouch.png',                           bgColor: '#EAE4DA', widthRatio: 0.85, heightRatio: 0.33, offsetX: -0.01, offsetY:  0.01, physicalWidthInches:  7.9, maxTextWidthInches: 6,    motifSizeInches: 0.75 },
  { name: "Grand Waffle Pouch",    bgImage: '/images/products/pouch/large_waffle_pouch.png',                           bgColor: '#EAE4DA', widthRatio: 0.84, heightRatio: 0.47, offsetX: -0.01, offsetY:  0.01, physicalWidthInches:  9,   maxTextWidthInches: 7,    motifSizeInches: 1.00 },
  { name: "Seersucker Pouch",      bgImage: null,                                                                       bgColor: '#EAE4DA', widthRatio: 0.60, heightRatio: 0.26, offsetX:  0.04, offsetY:  0.13, physicalWidthInches: 11,   maxTextWidthInches: 7,    motifSizeInches: 1.00 },
  { name: "Linen Cocktail Napkin", bgImage: '/images/products/napkin/napkin.PNG',                                       bgColor: '#F5F2EE', widthRatio: 0.53, heightRatio: 0.45, offsetX:  0.00, offsetY: -0.01, physicalWidthInches:  6,   maxTextWidthInches: 4,    motifSizeInches: 1.00 },
  { name: "The Oxford",            bgImage: null,                                                                       bgColor: '#EDE9E3', widthRatio: 0.60, heightRatio: 0.40, offsetX:  0.00, offsetY:  0.00, physicalWidthInches: 10,   maxTextWidthInches: 5,    motifSizeInches: 1.00 },
]

export type Preset = typeof PRESETS[number]
